-----------------------------------
-- HorizonXI Lua Module
-- Used to change item luas.
-----------------------------------
require("modules/module_utils")
require("scripts/globals/status")
-----------------------------------
local m = Module:new("horizon_item_luas")

m:addOverride("xi.globals.items.plate_of_fatty_tuna_sushi.onEffectGain", function(target, effect)
    target:addMod(xi.mod.HP, 20)
    target:addMod(xi.mod.DEX, 5)
    target:addMod(xi.mod.CHR, 5)
    target:addMod(xi.mod.FOOD_ACCP, 15)
    target:addMod(xi.mod.FOOD_ACC_CAP, 55)
    target:addPetMod(xi.mod.HP, 20)
    target:addPetMod(xi.mod.DEX, 3)
    target:addPetMod(xi.mod.CHR, 5)
    target:addPetMod(xi.mod.FOOD_ACCP, 15)
    target:addPetMod(xi.mod.FOOD_ACC_CAP, 55)
end)

m:addOverride("xi.globals.items.plate_of_fatty_tuna_sushi.onEffectLose", function(target, effect)
    target:delMod(xi.mod.HP, 20)
    target:delMod(xi.mod.DEX, 5)
    target:delMod(xi.mod.CHR, 5)
    target:delMod(xi.mod.FOOD_ACCP, 15)
    target:delMod(xi.mod.FOOD_ACC_CAP, 55)
    target:delPetMod(xi.mod.HP, 20)
    target:delPetMod(xi.mod.DEX, 3)
    target:delPetMod(xi.mod.CHR, 5)
    target:delPetMod(xi.mod.FOOD_ACCP, 15)
    target:delPetMod(xi.mod.FOOD_ACC_CAP, 55)
end)

m:addOverride("xi.globals.items.plate_of_ikra_gunkan.onEffectGain", function(target, effect)
    target:addMod(xi.mod.HP, 20)
    target:addMod(xi.mod.DEX, 5)
    target:addMod(xi.mod.VIT, 5)
    target:addMod(xi.mod.FOOD_ACCP, 12)
    target:addMod(xi.mod.FOOD_ACC_CAP, 52)
    target:addMod(xi.mod.FOOD_DEFP, 18)
    target:addMod(xi.mod.FOOD_DEF_CAP, 65)
end)

m:addOverride("xi.globals.items.plate_of_ikra_gunkan.onEffectLose", function(target, effect)
    target:delMod(xi.mod.HP, 20)
    target:delMod(xi.mod.DEX, 5)
    target:delMod(xi.mod.VIT, 5)
    target:delMod(xi.mod.FOOD_ACCP, 12)
    target:delMod(xi.mod.FOOD_ACC_CAP, 52)
    target:delMod(xi.mod.FOOD_DEFP, 18)
    target:delMod(xi.mod.FOOD_DEF_CAP, 65)
end)

m:addOverride("xi.globals.items.plate_of_ikra_gunkan_+1.onEffectGain", function(target, effect)
    target:addMod(xi.mod.HP, 20)
    target:addMod(xi.mod.DEX, 5)
    target:addMod(xi.mod.VIT, 5)
    target:addMod(xi.mod.FOOD_ACCP, 13)
    target:addMod(xi.mod.FOOD_ACC_CAP, 57)
    target:addMod(xi.mod.FOOD_DEFP, 20)
    target:addMod(xi.mod.FOOD_DEF_CAP, 70)
end)

m:addOverride("xi.globals.items.plate_of_ikra_gunkan_+1.onEffectLose", function(target, effect)
    target:delMod(xi.mod.HP, 20)
    target:delMod(xi.mod.DEX, 5)
    target:delMod(xi.mod.VIT, 5)
    target:delMod(xi.mod.FOOD_ACCP, 13)
    target:delMod(xi.mod.FOOD_ACC_CAP, 57)
    target:delMod(xi.mod.FOOD_DEFP, 20)
    target:delMod(xi.mod.FOOD_DEF_CAP, 70)
end)

m:addOverride("xi.globals.items.plate_of_tuna_sushi.onEffectGain", function(target, effect)
    target:addMod(xi.mod.HP, 20)
    target:addMod(xi.mod.DEX, 5)
    target:addMod(xi.mod.CHR, 5)
    target:addMod(xi.mod.FOOD_ACCP, 14)
    target:addMod(xi.mod.FOOD_ACC_CAP, 52)
    target:addPetMod(xi.mod.HP, 20)
    target:addPetMod(xi.mod.DEX, 3)
    target:addPetMod(xi.mod.CHR, 5)
    target:addPetMod(xi.mod.FOOD_ACCP, 14)
    target:addPetMod(xi.mod.FOOD_ACC_CAP, 52)
end)

m:addOverride("xi.globals.items.plate_of_tuna_sushi.onEffectLose", function(target, effect)
    target:delMod(xi.mod.HP, 20)
    target:delMod(xi.mod.DEX, 5)
    target:delMod(xi.mod.CHR, 5)
    target:delMod(xi.mod.FOOD_ACCP, 14)
    target:delMod(xi.mod.FOOD_ACC_CAP, 52)
    target:delPetMod(xi.mod.HP, 20)
    target:delPetMod(xi.mod.DEX, 3)
    target:delPetMod(xi.mod.CHR, 5)
    target:delPetMod(xi.mod.FOOD_ACCP, 14)
    target:delPetMod(xi.mod.FOOD_ACC_CAP, 52)
end)

return m
